print("program ngentod")
print("1.pilih lonte")
print("2.tempat")
print("3.ngntd")
menu = int(input("pilih menu"))
if menu==1:
    print("pilih lonte")
    print("1.mia khalifa")
    print("2.derika tod")
    print("3.vina :v")
    menu=int(input("pilih menu"))
    print("1.mia khalifa")
if menu==2:
    print("1.hotel")
    print("2.tempat rongsokan")
    print("3.bangunan kosong")
    menu2=int(input("input"))
    print("rongsokan")
if menu==3:
    print("masukin tytyd lu")
    menu3=int(input("pilih menu"))
    print("ah ah ah ah")
    menu3=int(input("pilih"))
    print("croot")